metwork-framework/mfextaddon_scientific

- layers/layer4_python3_scientific/0500_extra_packages/requirements-to-freeze.txt
- layers/layer4_python3_scientific/0500_extra_packages/requirements3.txt
> [WIP] feat: add cfgrib and xarray

- layers/layer1_scientific/0030_eccodes/Makefile.mk
- layers/layer1_scientific/0030_eccodes/sources
- layers/layer4_python2_scientific/0611_eccodes/Makefile.mk
- layers/layer4_python2_scientific/0611_eccodes/sources
- layers/layer4_python3_scientific/0611_eccodes/Makefile.mk
- layers/layer4_python3_scientific/0611_eccodes/sources
To merge only if build on branch pci_update_eccodes is ok.
> feat: upgrade eccodes from 2.10.0 to 2.12.5

- .drone.yml
This reverts commit 12355739081752c6071e40c9574254dd66265e95.
> Revert "test: temporary remove integration tests"

- .metwork-framework/components.md
- integration_tests/0003_test_import_python3_scientific/import_python3_scientific.py
- layers/layer4_python3_scientific/0500_extra_packages/Makefile
- layers/layer4_python3_scientific/0500_extra_packages/Makefile.mk
- layers/layer4_python3_scientific/0500_extra_packages/requirements-to-freeze.txt
- layers/layer4_python3_scientific/0500_extra_packages/requirements3.txt
Close: https://github.com/metwork-framework/mfext/issues/799
> feat: add opencv-contrib-python-headless

- .metwork-framework/components.md
- layers/layer1_scientific/0070_protobuf/Makefile
- layers/layer1_scientific/0070_protobuf/Makefile.mk
- layers/layer1_scientific/0070_protobuf/sources
- layers/layer4_python2_scientific/0499_extra_packages/requirements2.txt
- layers/layer4_python3_scientific/0499_extra_packages/requirements3.txt
> feat: add protobuf (protoc binary, C++ libraries and python2/3 packages)

- layers/layer4_python2_scientific/0499_extra_packages/requirements-to-freeze.txt
- layers/layer4_python2_scientific/0499_extra_packages/requirements2.txt
- layers/layer4_python3_scientific/0499_extra_packages/requirements-to-freeze.txt
- layers/layer4_python3_scientific/0499_extra_packages/requirements3.txt
> feat: add msgpack python module

- .metwork-framework/components.md
- integration_tests/0003_test_import_python2_scientific/import_python2_scientific.py
- integration_tests/0003_test_import_python3_scientific/import_python3_scientific.py
- layers/layer4_python2_scientific/0499_extra_packages/requirements-to-freeze.txt
- layers/layer4_python2_scientific/0499_extra_packages/requirements2.txt
- layers/layer4_python3_scientific/0499_extra_packages/requirements-to-freeze.txt
- layers/layer4_python3_scientific/0499_extra_packages/requirements3.txt
> fix: upgrade MetPy to 0.12.2 for compatibility with Cartopy 0.18

- .metwork-framework/components.md
- integration_tests/0003_test_import_python3_scientific/import_python3_scientific.py
- layers/layer4_python3_scientific/0499_extra_packages/requirements-to-freeze.txt
- layers/layer4_python3_scientific/0499_extra_packages/requirements3.txt
> feat: add python packages regionmask and salem

- .metwork-framework/components.md
- integration_tests/0003_test_import_python3_scientific/import_python3_scientific.py
- layers/layer4_python3_scientific/0499_extra_packages/requirements-to-freeze.txt
- layers/layer4_python3_scientific/0499_extra_packages/requirements3.txt
- layers/layer4_python3_scientific/0500_extra_packages/requirements-to-freeze.txt
- layers/layer4_python3_scientific/0500_extra_packages/requirements3.txt
> feat: add ot-batman and dependencies

- .metwork-framework/components.md
- layers/layer4_python3_scientific/0498_prereq_extra_packages/requirements3.txt
- layers/layer4_python3_scientific/0500_extra_packages/requirements3.txt
> feat: upgrade pandas from 0.24.2 to 1.2.4

- layers/layer1_scientific/0008_pango/Makefile.mk
> feat: build pango with xft support

- .metwork-framework/components.md
- integration_tests/0003_test_import_python3_scientific/import_python3_scientific.py
- layers/layer4_python3_scientific/0500_extra_packages/Makefile.mk
- layers/layer4_python3_scientific/0500_extra_packages/requirements-to-freeze.txt
- layers/layer4_python3_scientific/0500_extra_packages/requirements3.txt
> feat: add python module pyhdf

- .metwork-framework/components.md
- layers/layer1_scientific/0030_eccodes/Makefile.mk
> feat: add fortran support to eccodes and upgrade eccodes and eccodes-python to last releases (2.23.0 and 1.3.3)

- .metwork-framework/components.md
- integration_tests/0003_test_import_python3_scientific/import_python3_scientific.py
- layers/layer1_scientific/0085_gmt/Makefile
- layers/layer1_scientific/0085_gmt/Makefile.mk
- layers/layer1_scientific/0085_gmt/sources
- layers/layer1_scientific/dcw_gmt/Makefile
- layers/layer1_scientific/dcw_gmt/Makefile.mk
- layers/layer1_scientific/dcw_gmt/sources
- layers/layer1_scientific/gshhg_gmt/Makefile
- layers/layer1_scientific/gshhg_gmt/Makefile.mk
- layers/layer1_scientific/gshhg_gmt/sources
- layers/layer4_python3_scientific/0500_extra_packages/requirements-to-freeze.txt
- layers/layer4_python3_scientific/0500_extra_packages/requirements3.txt
> feat: add GMT with GSHHG and DCW geographical data and python3 api pygmt

- layers/layer0_scientific_system_libraries/0001_libraries/libraries.txt
This reverts commit b6bafe0de7aaf7184b19e610c152dc1312a3d589.
> build: revert add libtiff.so.3 as system dependency

- integration_tests/0002_test_import_python3_scientific/import_python3_scientific.py
- layers/layer4_python3_scientific/0500_extra_packages/Makefile.mk
This reverts commit 76b9ad5211842451bde237566c29ec1d3f432eaf.
> build: Revert "build: temporarly remove test on pycurl (#312)"

- layers/layer1_scientific/.system_dependencies
- layers/layer1_scientific/0040_imagemagick6/Makefile.mk
- layers/layer1_scientific/0080_ffmpeg/Makefile.mk
and a few other supports in ffmpeg
> feat: add rsvg support in ImageMagick and ffmpeg

- .metwork-framework/components.md
- layers/layer4_python3_scientific/0500_extra_packages/requirements3.txt
This reverts commit 61222ad90050dd1fb0d6cf8a2a517a5ffbe2dd21.
> feat: back to cligj 0.5.0, fiona 1.8.13 and rasterio 1.1.5 (revert)

- .metwork-framework/components.md
- layers/layer1_scientific/0030_eccodes/Makefile.mk
- layers/layer4_python3_scientific/.layerapi2_extra_env
- layers/layer4_python3_scientific/0500_extra_packages/requirements3.txt
> fix: fix bad behavior of eccodes-python in the presence of ecmwflibs

- .metwork-framework/components.md
- layers/layer4_python3_scientific/0500_extra_packages/requirements3.txt
> feat: upgrade lxml from 4.6.5 to 4.9.1 (security update)

- .metwork-framework/components.md
- layers/layer4_python3_scientific/0499_prereq_extra_packages/requirements-to-freeze.txt
- layers/layer4_python3_scientific/0499_prereq_extra_packages/requirements3.txt
This reverts commit 7a9ea6388623dcfeb240308b477efe800c3dcc09.
> build: revert add versioneer for dask build

- .metwork-framework/components.md
- layers/layer4_python3_scientific/0500_extra_packages/requirements-to-freeze.txt
- layers/layer4_python3_scientific/0500_extra_packages/requirements3.txt
Close: https://github.com/metwork-framework/mfextaddon_scientific/security/dependabot/46
> feat: fork of configobj to address CVE-2023-26112, thanks to cdcadman

- .metwork-framework/components.md
- layers/layer4_python3_scientific/0500_extra_packages/requirements3.txt
... and downgrade ecmwflibs to 0.5.3 as ECMWF is doing strange things (to stay polite) about manylinux wheels on pypi
(see https://github.com/ecmwf/ecmwflibs/issues/29)
> feat: bump GDAL from 3.8.0 to 3.8.1

- .metwork-framework/components.md
- layers/layer4_python3_scientific/0500_extra_packages/requirements3.txt
(for compatibility with setuptools >= 70)
> feat: upgrade astropy to 6.1.2 and scitools-iris to 3.10.0

- .metwork-framework/components.md
- layers/layer4_python3_scientific/0500_extra_packages/requirements-to-freeze.txt
- layers/layer4_python3_scientific/0500_extra_packages/requirements3.txt
(see https://github.com/NREL/floris/issues/1030)
> feat: temporarly remove FLORIS and dependencies, waiting for numpy 2.0 compatibility

- .metwork-framework/components.md
- layers/layer4_python3_scientific/0499_prereq_extra_packages/requirements3.txt
> feat: bump extension-helpers to 1.2.0 (usage of tomllib rather than tomli)

- .metwork-framework/components.md
- layers/layer4_python3_scientific/0500_extra_packages/allow_binary_packages
- layers/layer4_python3_scientific/0500_extra_packages/requirements3.txt
(also add dependencies odclib 1.6.0 and eckitlib 1.29.2)
> feat: bump pyodc from 1.3.0 to 1.6.0
